<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>gpm</AssemblyName>
    <RootNamespace>GitProfileManager</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <DebugType>embedded</DebugType>
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConsoleAppFramework" Version="5.4.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" Version="16.3.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference Include="Jab" Version="0.11.0" />
    <PackageReference Include="Raiqub.JabModules.MicrosoftExtensionsOptions" Version="1.0.16" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.3" />
    <PackageReference Include="Velopack" Version="0.0.1053" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="GitProfileManager.Commands" />
    <Using Include="ConsoleAppFramework" />
    <Using Include="Jab" />
    <Using Include="Raiqub.JabModules.MicrosoftExtensionsOptions" />
    <Using Include="Microsoft.Extensions.Configuration" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Microsoft.Extensions.Logging.LoggerFactory" Alias="MSLogger" />
    <Using Include="Microsoft.Extensions.Options" />
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitProfileManager.Lib\GitProfileManager.Lib.csproj" />
  </ItemGroup>
</Project>