<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>gpm</AssemblyName>
    <RootNamespace>GitProfileManager</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <DebugType>embedded</DebugType>
    <MinVerDefaultPreReleaseIdentifiers>preview</MinVerDefaultPreReleaseIdentifiers>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MinVer" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ConsoleAppFramework" Version="5.6.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Spectre.Console" Version="0.51.1" />
    <PackageReference Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" Version="16.3.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference
      Include="Microsoft.Extensions.Configuration"
      Version="10.0.0-rc.1.25451.107"
    />
    <PackageReference
      Include="Microsoft.Extensions.Configuration.Binder"
      Version="10.0.0-rc.1.25451.107"
    />
    <PackageReference
      Include="Microsoft.Extensions.Configuration.Json"
      Version="10.0.0-rc.1.25451.107"
    />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0-rc.1.25451.107" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="GitProfileManager.Commands" />
    <Using Include="ConsoleAppFramework" />
    <Using Include="Jab" />
    <Using Include="Raiqub.JabModules.MicrosoftExtensionsOptions" />
    <Using Include="Microsoft.Extensions.Configuration" />
    <Using Include="Microsoft.Extensions.Logging" />
    <Using Include="Microsoft.Extensions.Logging.LoggerFactory" Alias="MSLogger" />
    <Using Include="Microsoft.Extensions.Options" />
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Serialization" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GitProfileManager.Lib\GitProfileManager.Lib.csproj" />
  </ItemGroup>
</Project>
